<?php declare(strict_types=1);
/**
 * e-Arc Framework - the explicit Architecture Framework
 *
 * @package earc/data
 * @link https://github.com/Koudela/eArc-data/
 * @copyright Copyright (c) 2019-2021 Thomas Koudela
 * @license http://opensource.org/licenses/MIT MIT License
 */

namespace eArc\Data\Entity\Interfaces\PrimaryKey;

use eArc\Data\Entity\Interfaces\EntityInterface;

/**
 * Exposes an entity to autogenerated keys via the `OnAutoPrimaryKey` event.
 */
interface AutoPrimaryKeyInterface extends PrimaryKeyInterface
{
    /**
     * Set the primary key of the entity. A string that is unique to the type of
     * object.
     *
     * @param string|null
     */
    public function setPrimaryKey(string|null $primaryKey): void;
}
